teams = ["",
    "Boston Red Stockings", "Chicago White Stockings", "Cleveland Forest Citys",
    "Fort Wayne Kekiongas", "New York Mutuals", "Philadelphia Athletics",
    "Rockford Forest Citys", "Troy Haymakers", "Washington Olympics", "Baltimore Canaries",
    "Brooklyn Eckfords", "Brooklyn Atlantics", "Middletown Mansfields", "Washington Nationals",
    "Baltimore Marylands", "Elizabeth Resolutes", "Philadelphia Whites", "Washington Blue Legs",
    "Hartford Dark Blues", "Keokuk Westerns", "New Haven Elm Citys", "Philadelphia Centennials",
    "St. Louis Red Stockings", "St. Louis Brown Stockings", "Boston Red Caps", "Cincinnati Reds",
    "Louisville Grays", "Indianapolis Blues", "Milwaukee Grays", "Providence Grays", "Buffalo Bisons",
    "Cleveland Blues", "Syracuse Stars", "Troy Trojans", "Worcester Ruby Legs", "Detroit Wolverines",
    "Baltimore Orioles", "Cincinnati Red Stockings", "Louisville Eclipse", "Pittsburg Alleghenys",
    "Boston Beaneaters", "Columbus Buckeyes", "New York Gothams", "New York Metropolitans",
    "Philadelphia Quakers", "St. Louis Browns", "Altoona Mountain City", "Baltimore Monumentals",
    "Boston Reds", "Chicago/Pittsburgh (Union League)", "Cincinnati Outlaw Reds", "Indianapolis Hoosiers",
    "Kansas City Cowboys", "Milwaukee Brewers", "Philadelphia Keystones", "Richmond Virginians",
    "St. Louis Maroons", "St. Paul White Caps", "Toledo Blue Stockings", "Wilmington Quicksteps",
    "Brooklyn Grays", "Louisville Colonels", "New York Giants", "Brooklyn Bridegrooms",
    "Cleveland Spiders", "Columbus Solons", "Brooklyn Gladiators", "Brooklyn Ward's Wonders",
    "Chicago Colts", "Chicago Pirates", "Cleveland Infants", "Philadelphia Phillies",
    "Pittsburgh Burghers", "Rochester Broncos", "Toledo Maumees", "Brooklyn Grooms",
    "Cincinnati Kelly's Killers", "Pittsburgh Pirates", "Washington Statesmen", "Washington Senators",
    "Chicago Orphans", "Brooklyn Superbas", "St. Louis Perfectos", "St. Louis Cardinals",
    "Boston Americans", "Chicago White Sox", "Detroit Tigers", "Cleveland Bronchos",
    "Chicago Cubs", "Cleveland Naps", "New York Highlanders", "Boston Doves",
    "Boston Red Sox", "Brooklyn Dodgers", "Boston Rustlers", "Boston Braves",
    "New York Yankees", "Baltimore Terrapins", "Brooklyn Tip-Tops", "Brooklyn Robins",
    "Buffalo Buffeds", "Chicago Chi-Feds", "Kansas City Packers", "Pittsburgh Rebels",
    "St. Louis Terriers", "Buffalo Blues", "Chicago Whales", "Cleveland Indians",
    "Newark Pepper", "Boston Bees", "Philadelphia Blue Jays", "Milwaukee Braves",
    "Cincinnati Redlegs", "Kansas City Athletics", "Los Angeles Dodgers", "San Francisco Giants",
    "Los Angeles Angels", "Minnesota Twins", "Houston Colt .45's", "New York Mets",
    "California Angels", "Houston Astros", "Atlanta Braves", "Oakland Athletics",
    "Kansas City Royals", "Montreal Expos", "San Diego Padres", "Seattle Pilots",
    "Texas Rangers", "Seattle Mariners", "Toronto Blue Jays", "Colorado Rockies",
    "Florida Marlins", "Anaheim Angels", "Arizona Diamondbacks", "Tampa Bay Devil Rays",
    "Los Angeles Angels of Anaheim", "Tampa Bay Rays", "Miami Marlins", "Cleveland Guardians"
]